version: '3'

services:
  db:
    build: ./db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "4455:4455"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_DSN=host=usermanagmenttask_db user=myuser password=mypassword dbname=mydb port=4455 sslmode=disable
    ports:
      - "8092:8093"
    command:
      - sh
      - -c
      - "sleep 3 && ./main"
