version: '3'

services:
  db:
    build: ./db
    env_file:
      - .env
    ports:
      - "4455:4455"

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8092:8093"
    command:
      - sh
      - -c
      - "sleep 3 && ./main"
