# Используем официальный образ PostgreSQL
FROM postgres:alpine

# Устанавливаем переменные окружения
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}